### ISSUE TITLE
Failed to attach BPF program b'kprobe__ipt_do_table' to kprobe b'ipt_do_table',

### ISSUE THREAD

**Issue by GitMaggie** [mYu4N/mytracer#2]
python mytracer.py  --iptable   

cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "mytracer.py", line 1006, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 484, in __init__
    self._trace_autoload()
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 1455, in _trace_autoload
    fn_name=fn.name)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 844, in attach_kprobe
    (fn_name, event))
Exception: Failed to attach BPF program b'kprobe__ipt_do_table' to kprobe b'ipt_do_table', it's not traceable (either non-existing, inlined, or marked as "notrace")

### uname -a 
 5.10.134-16.3.al8.x86_64 #1 SMP Tue Mar 26 18:54:05 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mYu4N** [comment]
this probe need kernel load this  module  ip_tables  iptable_filter,iptable_raw,iptable_nat,iptable_mangle
